# Generated by Django 5.0 on 2023-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_options_messages_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='privateKey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privateKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
